steps:
  - label: check-cc1
    command: .ci/scripts/run-gradle-cc.sh :server:precommit
    timeout_in_minutes: 300
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2004
      machineType: custom-32-98304
      buildDirectory: /dev/shm/bk
